# Config file for automatic testing at travis-ci.org
language: python
python:
  - 3.6
addons:
  apt:
    packages:
      - chromium-chromedriver
install:
  - pip install --upgrade pip
  - pip install $DJANGO_VERSION --upgrade
  - pip install oauth2client==1.5.2
  - django-admin.py --version
  - pip install selenium
before_script:
  - export PATH=$PATH:/usr/lib/chromium-browser/
  - cd testapp/app && python manage.py runserver
  - sleep 3
env:
  global:
    - DJANGO_VERSION='Django>=2.2,<3.0'
    - DJANGO_VERSION='Django>=3.0,<3.1'
    - CHROME_DRIVER_PATH='/usr/lib/chromium-browser/chromedriver'
script:
  - cd testapp/app && python manage.py test
branches:
  only:
    - master
    - feature/e2e-tests
sudo: false
